/* empty css                      */(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function d(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".demo-btn"),o=document.getElementById("gameIframe"),i=document.getElementById("closeIframeBtn");c&&o&&i&&(c.addEventListener("click",d=>{d.preventDefault();const e=c.getAttribute("data-game-url");o.src=e,o.style.display="block",i.style.display="flex"}),i.addEventListener("click",()=>{o.style.display="none",i.style.display="none",o.src=""}))});document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".menu-button"),o=c.querySelector(".icon"),i=document.querySelector(".modal"),d=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const a=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="11.5" stroke="#EFB00D" />
  <path d="M5.625 7.125H18.375M5.625 16.125H18.375M5.625 11.625H18.375" stroke="#D0D0D4" stroke-linecap="round" />
</svg>
    `,n=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="11.5" stroke="#EFB00D" />
  <path d="M5.25 5.25L12 12M12 12L5.25 18.75M12 12L18.75 18.75M12 12L18.75 5.25" stroke="#D0D0D4" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;c.addEventListener("click",()=>{t=!t,o.innerHTML=t?n:a,t?s():r()}),d.forEach(u=>u.addEventListener("click",()=>{r(),o.innerHTML=a,t=!1})),window.addEventListener("scroll",l);function s(){i.style.display="block"}function r(){i.style.display="none"}function l(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function c(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const s=document.getElementById(n);if(!s)return;const r=c(),l=s.getBoundingClientRect().top+window.pageYOffset-r;window.scrollTo({top:l,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(s){const r=this.getAttribute("href");if(!r)return;const[l,u]=r.split("#");if(!u)return;const m=window.location.pathname.split("/").pop();!(l===""||l==="./"||l===m||l==="./"+m)||!document.getElementById(u)||(s.preventDefault(),o(u),t(u))})});const d=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(n){e.forEach(r=>r.classList.remove("active"));const s=document.querySelector(`.navigation-item a[href*="#${n}"]`);s&&s.closest(".navigation-item").classList.add("active")}function a(){const n=window.pageYOffset+c()+100;d.forEach(s=>{const r=s.offsetTop,l=r+s.offsetHeight;n>=r&&n<l&&t(s.id)})}if(window.addEventListener("scroll",a),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{o(n),t(n)},300)}});document.addEventListener("DOMContentLoaded",function(){const c=document.getElementById("cookie-popup"),o=document.getElementById("accept-cookies"),i=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(c.style.display="block"),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),c.style.display="none"}),i.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),c.style.display="none"})});
//# sourceMappingURL=index.js.map
